name: Continuous Deployment Workflow

on:
  workflow_dispatch:

jobs: 

  terraform:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Destroy on Failure
        if: failure()  # Выполнится только если apply упал
        run: terraform destroy -auto-approve
      
  ansible:
    name: Configure Servers with Ansible
    runs-on: ubuntu-latest
    needs: [terraform]
    steps:
      - uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          # boto3 подхватит настройки от шага "Configure AWS Credentials" автоматически
          pip install ansible boto3 botocore docker
          # Install amazon.aws collection for EC2 dynamic inventory
          ansible-galaxy collection install amazon.aws

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/latest.pem
          chmod 600 ~/.ssh/latest.pem

      - name: Debug Inventory
        run: ansible-inventory -i inventory/aws_ec2.yaml --graph

      - name: Run Ansible Playbook
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_IMAGE }}
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_FORCE_COLOR: "true"
        run: |
          ansible-playbook -i inventory/aws_ec2.yaml pet-playbook.yaml \
          -u ec2-user \
          --private-key ~/.ssh/latest.pem
